### PR TITLE
Add headC, headDefC and lastDefC combinators

### PR DESCRIPTION
**Pull request by k0ral**
I find myself reimplementing those combinators in several of my projects.
What about providing them upstream ?

### CODE REVIEW

**Comment by snoyberg** [comment]
For consistency, can you add the non-suffixed versions of the functions to `Data.Conduit.Combinators` as well, and update the changelog about the new additions?

**Comment by k0ral** [comment]
Done. I had to presume a version bump to 1.0.5, I hope that's ok.

**Comment by snoyberg** [comment]
Beautiful! Just waiting on Travis and then I'll merge. Thanks!

**Comment by snoyberg** [comment]
Merging despite the Travis failures, they're unrelated. Thanks!

**Pull request merged**
