### PR TITLE
Initial MonoApplicative

### PR DESCRIPTION
**Pull request by sheganinans**
Tentative MonoApplivative instance corresponding free instances.

### CODE REVIEW

**Comment by snoyberg** [comment]
:-1:, with this naming, `MonoApplicative` has a different kind than `MonoFunctor`, and `MonoFunctor` cannot imply `MonoApplicative`, which I find very confusing.

**Comment by sheganinans** [comment]
Sure, I don't mind bikeshedding it a bit. What would you recommend?

**Comment by snoyberg** [comment]
My original concern still exists outside of the naming concern: I don't see how this fits in with the rest of mono-traversable, and any inclusion of a monomorphic container of kind `* -> *` would be a strange addition.

**Comment by sheganinans** [comment]
Ok, this could go in a separate project. Thanks!

**Pull request closed without merging**
