### PR TITLE
Relax MonoTraversable constraint on IsSequence

### PR DESCRIPTION
**Pull request by kbillings**

### CODE REVIEW

**Comment by snoyberg** [comment]
This is actually a breaking change. What's the motivation for relaxing this constraint? Are there data types out there which would fit `IsSequence` but are not `MonoTraversable`?

**Comment by snoyberg** [comment]
Also: thanks for all of the great documentation enhancements :)

**Comment by kbillings** [comment]
@snoyberg
I thought there was no reason on constricting `IsSequence` to `MonoTraversable`. Every `MonoTraversable` is also a `MonoFoldable` and nothing in `IsSequence`'s functions require anything from `MonoTraversable`, only from `MonoFoldable`.

**Comment by gregwebs** [comment]
why is this a breaking change?

The classic example here would be a `Set`. A `Set` supports `fromList`. Right now for a `Set` instance to make sense for `IsSequence` we would need either a finer-grained approach to your typeclasses or to define (possibly with a newtype) a stable ordering (probably increasing or decreasing) for some of the operations to make sense.

**Comment by kbillings** [comment]
@gregwebs 
I think this would break things like:
```haskell
f :: (IsSequence seq, Applicative f) => (Element seq -> f (Element seq)) -> seq -> f seq
f tr = otraverse tr . take 10
```
Or anything that takes in a `IsSequence` and expects it to be `MonoTraversable`.

**Comment by gregwebs** [comment]
Ahh, right. Still, I doubt it will cause a lot of problems and is easy to fix even in a backwards compatible way. So I think breakage in this case is a reason for a version bump but not a reason to hold up a change.

**Comment by snoyberg** [comment]
`Set` is the perfect example of why I chose `MonoTraversable` as the constraint: it *shouldn't* be an instance is `IsSequence`, since it doesn't behave like other sequences. For example, for all other sequences, `length a + length b = length (a <> b)`, which doesn't hold for `Set`.

**Comment by kbillings** [comment]
@snoyberg `Set` wouldn't be an instance of `IsSequence` anyway with the `MonoTraversable` -> `MonoFoldable` change. `Set` would need to be an instance of `SemiSequence` to be an instance of `IsSequence`, which it isn't.

**Comment by snoyberg** [comment]
@kbillings Which brings me back to my original question: are there any examples of a data type that should be an `IsSequence` but should not be a `MonoTraversable`? It seems to me like retaining structure over monadic/applicative mapping should be a prerequisite for anything which is sequence-like.

**Comment by kbillings** [comment]
@snoyberg I don't know of any data types that should be an instance of `IsSequence` but not an instance of `MonoTraversable`. The fact that a data type needs to have `MonoTraversable` to be a sequence is only an abstract constraint and not a code constraint because nothing in `IsSequence` actually uses `otraverse`. So this pull request doesn't really matter unless someone creates a data type that is a sequence but is not traversable.

**Comment by gregwebs** [comment]
I am generally not in favor of abstract constraints, although I will admit that it may be conceptually ok in this case. One burden this does for the creator of a data structure is to define the MonoTraversable instance even if they would not otherwise need to bother with it.

Eventually I want a weaker intermediary `Buildable` structure that has these laws:

```
toList . fromList . toList === toList
fromList . toList . fromList === fromList
```

**Comment by kbillings** [comment]
Ok, I'll close this pull request since this change doesn't seem to be needed.

**Pull request closed without merging**
