### PR TITLE
Add 'asum' consumer

### PR DESCRIPTION
**Pull request by k0ral**
Not satisfied with the name `orA`...

### CODE REVIEW

**Comment by snoyberg** [comment]
How about [asum](https://www.stackage.org/haddock/lts-8.3/base-4.9.1.0/Data-Foldable.html#v:asum)? And can I recommend as well:

* Adding to the .Unqualified module with a `C` extension
* Not sure about this: does it make sense to make an `asumE` for elements of the stream?

**Comment by k0ral** [comment]
Am I supposed to use `gen-unqualified.hs` script ? Because it looks as if it weren't used for some time:

- I had to remove some end-of-lines in `Combinators.hs` to have it correctly parse signatures
- the generated code significantly differs from the existing one from `Unqualified.hs`: missing functions are added, import list is different, haddock comments are changed, inline pragmas are added... it looks better actually.

Regarding `asumE`, I don't see the need to define it, `mapC asum` isn't that tiresome to type :) .

**Comment by k0ral** [comment]
Actually, the generated file doesn't build, so I'm manually adding `asumC`.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
