### PR TITLE
Fix building with time>=1.10

### PR DESCRIPTION
**Pull request by TeofilC**
Thanks to @ocharles for [spotting](https://github.com/snoyberg/mono-traversable/pull/205#issuecomment-986593036) this issue.

I've added the extra imports required to make this build, and bumped the version.
I used qualified imports to avoid more of Data.Time being re-exported

### CODE REVIEW

**Comment by snoyberg** [comment]
Would it be possible to add an additional stack.yaml that has a time in extra-deps that demonstrates the patch is working?

**Comment by TeofilC** [comment]
I've added a stack yaml that should allow  testing newer versions of time. I picked `time-1.10` as it seems to be the only version that has this change and is both compatible with lts-16 and lts-18.

I've also added this new stack yaml to the Github action's matrix

**Comment by TeofilC** [comment]
Alright appears like lts-16 and time-1.10 are not compatible unfortunately, so I've excluded that combination.
(It appeared fine locally as I had `system-ghc: true` set and was using 8.10)

**Comment by TeofilC** [comment]
It looks like one of the windows failures is due to https://github.com/jacobstanley/unix-compat/pull/47

**Comment by snoyberg** [comment]
I'd recommend simply skipping the time 1.10 build on Windows.

**Comment by TeofilC** [comment]
Sounds good. I've removed that job

**Comment by snoyberg** [comment]
Thanks!

**Comment by ocharles** [comment]
Thanks both, this is now working on GHC 9.2 :+1:

**Pull request merged**
