### PR TITLE
Add filterWithKey and bump classyprelude cabal version

### LINKED ISSUE #218: Filtering with key
there are methods in the Containers module for filtering values within a container, but unlike many other functions there is not a method to filter with the container key. Would it be possible to add that to the typeclasses?

### PR DESCRIPTION
**Pull request by L0neGamer**
closes #218

also adding dist-newstyle to the gitignore list

@BebeSparkelSparkel

### CODE REVIEW

**Comment by BebeSparkelSparkel** [comment]
@L0neGamer Please add to mono-traversable/ChangeLog.md

**Comment by BebeSparkelSparkel** [comment]
@gregwebs When working with snoyberg on PRs he did not have me up the prelude versions when functionality was added to mono-traversable. What is your opinion on this?

Considering that ClassyPrelude.hs imports with hiding it does not make sense to me to up the version if the dependencies export more.

**Comment by gregwebs** [comment]
yeah classy prelude only needs to be bumped if it is exporting new things.

**Comment by BebeSparkelSparkel** [comment]
The version of classy-prelude should remain unchanged.

**Comment by L0neGamer** [comment]
the version is unchanged, I used the wrong language; the cabal file was updated because stack was run at some point.

**Comment by BebeSparkelSparkel** [comment]
@L0neGamer #234 fixed the classy-prelude cabal version. Try rebasing on master and ensure that classy-prelude/classy-prelude.cabal is unchanged and this should be ready to pull.

**Comment by BebeSparkelSparkel** [comment]
@L0neGamer Thanks for the help!
@gregwebs Appreciate the input!

**Pull request merged**
